name: Deploy to Firebase

permissions: read-all

on:
  push:
    branches:
      - main  # Triggers when a PR is merged into main
  workflow_dispatch:  # Allow manual triggers from GitHub Actions UI

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: "20"
          cache: "npm"

      - name: Install root dependencies
        run: npm ci

      - name: Install functions dependencies
        run: npm ci
        working-directory: functions

      - name: Build Next.js
        run: |
          rm -rf public/_next public/index.html public/404.html
          npm run build

      - name: Copy build artifacts
        run: node scripts/copy-build.js

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@c200f3691d83b41bf9bbd8638997a462592937ed
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}


      - name: Deploy to Firebase
        run: npx firebase-tools deploy --only functions,hosting:site --project organic-spirit-488116-e2 --non-interactive --force
